# Generated by Django 3.0.5 on 2020-04-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=255)),
                ('Secret', models.CharField(max_length=255)),
                ('Active', models.CharField(choices=[('A', 'ACTIVE'), ('N', 'NOTACTIVe')], max_length=1)),
            ],
        ),
    ]
